### ISSUE TITLE
Add remote-control methods to Automato class

### ISSUE THREAD

**Issue by chronopoulos** [InterstitialTech/automato-library#1]
Add these remote-control methods to the Automato class:

bool Automato::remotePinMode(uint32_t address, uint8_t pin, uint8_t mode);
bool Automato::remoteDigitalWrite(uint32_t address, uint8_t pin, uint8_t value);
bool Automato::remoteDigitalRead(uint32_t address, uint8_t pin, uint8_t *result);

The return values of these methods should be boolean true or false reflecting the success or failure (ACK/NAK) of the transaction. If successful, remoteDigitalRead() should modify the variable pointed to by "result".

Behind the scenes, this will involve the specification of a messaging protocol, and the implementation of a loop which handles incoming messages:

uint8_t Automato::parseLoop(void);
(return value is a error code in case the loop needs to break out)

which for now can just run as a blocking function call on the slave device. Eventually, we'll want to launch this as a FreeRTOS thread from Automato::init()

**Comment by bburdette** [comment]
Flagging this as basically-complete.  RTOS thread is not implemented yet, but remote control methods are in place.  Esp32 has a lot of analog pin functions that are unimplemented as of now, and we're putting those off until later.

**Comment by bburdette** [comment]
See #2, #3,  #4
